title:             Carrey's 개발 블로그
email:             jaehun2841@gmail.com
description:       "경험하고, 공부하면 이 곳에 남겨 기억을 보존하자"
author:            Carrey
baseurl:           "/"
url:               ""

# Social Profiles
twitter_username:  ""
github_username:   jaehun2841
facebook_username: "" 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
