title:             Carrey's 개발 블로그
email:             jaehun2841@gmail.com
description:       A Blog Theme by Start Bootstrap
author:            Carrey
baseurl:           "/"
url:               ""

# Social Profiles
twitter_username:  ""
github_username:   jaehun2841
facebook_username: "" 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
