# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Carrey`s 기술블로그
subtitle: 돈이 되는 블로그
author: Carrey
language: lang
timezone: Asia/seoul

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite-url       # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: Carrey`s 기술블로그
email: jaehun2841@gmail.com
description: ""
keyword: ""
header-img: img/header_img/home-bg-2-dark.png
signature: true #show signature
signature-img: img/signature/BeanTechSign-white.png 


# SNS settings
# RSS: false
# weibo_username:     Demonbaneen
# zhihu_username:     Demonbane
github_username:    jaehun2841
# twitter_username:   Demonbane_x
#facebook_username:  YenYuHsuan
#linkedin_username:  yu-hsuan-yen

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username: your-disqus-ID

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-XXXXXXXX-X'          # Format: UA-xxxxxx-xx
ga_domain: yoursite


# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "일을 하면서 배우는 지식과 별도로 공부한 지식을 정리한 블로그입니다."
sidebar-avatar: img/ironman-draw.png      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
- category

# widget behavior
## Archive
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


## Friends
# friends: [
#     {
#         title: "Bean Tech",
#         href: "http://beantech.org"
#     },{
#         title: "Kaijun's Blog",
#         href: "http://blog.kaijun.rocks"
#     },{
#         title: "Hux Blog",
#         href: "http://huangxuan.me"
#     },{
#         title: "It Helps SEO",
#         href: "#"
#     }
# ]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: true
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# assets
asset_path:
enable: true

# Asset folder, used when post asset folder is not enabled.
# For example, the following asset folder configuration will make hexo to use "/r12f-assets/post-assets/2017-01-16-Hello-World" as the base URL in one of my post.
asset_folder: /

# CDN settings, and CDN folder will always be considered to have its own domain and start from the root.
enable_cdn: true
cdn_folder: jaehun2841.github.io
cdn_use_https: false

# Selectors and attribute names for getting the elements to update.
selectors:
  img[src]: 'src'

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: beantech

#sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/jaehun2841/jaehun2841.github.io
  branch: master
