# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Carrey`s 기술블로그
subtitle: 공부하고, 경험하고, 삽질해서 얻은 지식들을 기록합니다.
author: Carrey
language: lang
timezone: Asia/seoul

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://jaehun2841.github.io       # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - googleb6989b051cadc23a.html 
  - naver06b931b9a92d9d3d74ae0c39217e61a6.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link.enabled: true # Open external links in new tab
filename_case: 0
render_drafts: true
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives
  
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: melody

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:jaehun2841/jaehun2841.github.io.git
  branch: gh-pages

# Crawler
sitemap:
  path: sitemap.xml

# rss feed auto generator
feed:
  # feed type (atom / rss2)
  type: rss2
  # feed path (Default: atom.xml / rss2.xml)
  path: rss2.xml
  # 최신 포스트의 갯수 설정. (0 또는 false 입력시 전체 포스트)
  limit: 20

# Coupang Adsense
coupang_adsense:
  top: 301414
  bottom: 301410